### ISSUE TITLE
!ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by rinabell** [itsuki8914/ESRGAN-TensorFlow#1]
hi there 
first of all I wanna say your code help me a lot, but it puzzles me when I run `python main.py` it went wrong with this:

> Traceback (most recent call last):
  File "main.py", line 300, in <module>
    main()
  File "main.py", line 170, in main
    batch_images_x, batch_images_t = batchgen.getBatch(bs)
  File "/media/media/sela/4esrgan/btgen.py", line 87, in getBatch
    img_y = cv2.resize(img_y,self.HRSize,interpolation = cv2.INTER_CUBIC)
cv2.error: OpenCV(4.0.1) /io/opencv/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
>

- I swear that I have put DIV2K database in proper folder as you wrote in readme.md precisely
- there is no problem with database and no 0-size picture in those 4 folders
- I also google for solution and reinstall my tensorflow/scipy/numpy packet
- my env: tf-gpu-1.14.0; numpy-1.16.4; scipy-1.3.0; opencv-python-4.0.1.24
- it is quite strange that it always went wrong **after** read several pictures in memory, like:

>2019-07-26 23:20:17.860949: W tensorflow/core/framework/allocator.cc:107] Allocation of 1849688064 exceeds 10% of system memory.
in step 1, pre_loss =4.6157e-01, L2_loss=3.3772e-01, vgg_loss=1.2384e-01
train_lr/0254x4.png train_hr/0331.png
train_lr/0035x4.png train_hr/0271.png
train_lr/0410x4.png train_hr/0195.png
train_lr/0733x4.png train_hr/0324.png
Traceback (most recent call last):
>

thanks again for looking into it

**Comment by rinabell** [comment]
looks like I found why, requests will pull soon after it be trained entirely
