### ISSUE TITLE
Range cannot be empty (low >= high) unless no samples are taken

### ISSUE THREAD

**Issue by ManoaNosea** [itsuki8914/ESRGAN-TensorFlow#4]
```λ python main.py
read images
8.2680 sec took reading
train_lr has 1205 files
read images
5.6004 sec took reading
val_lr has 1205 files
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    main()
  File "main.py", line 65, in main
    IN_ , OUT_ = batchgen.getBatch(4)[:4]
  File "F:\dod2\ESRGAN-TensorFlow-master\btgen.py", line 51, in getBatch
    img_x , img_y = self.crop(img_lr, img_hr)
  File "F:\dod2\ESRGAN-TensorFlow-master\btgen.py", line 38, in crop
    x = np.random.randint(0, w - self.LRSize[1]-1)
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken

**Comment by itsuki8914** [comment]
What dataset are you using?
You are probably using a smaller image than necessary.
Small images need to be removed.
Images need to be larger than 96 * 96 for training and evaluation while training. This value can be changed. (Line 55 of main.py)
On the other hand, pred.py can handle images of any size. (within memory)
