### ISSUE TITLE
Tensor shape mismatch

### ISSUE THREAD

**Issue by ntreepoint** [itsuki8914/ESRGAN-TensorFlow#5]
Hi,
When trying to train the model, i have the following error:
```
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    main()
  File "main.py", line 172, in main
    t: batch_images_t
  File "/home/envs/esrgan/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/anaconda3/envs/esrgan/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4, 96, 96, 3) for Tensor u'vgg19/conv5_4/b:0', which has shape '(512,)'
```
I use vgg19.npy as indicated in the readme. Did you already get this kind of error?

**Comment by itsuki8914** [comment]
Is your python version 2.7?
If you have an older version of python or TensorFlow, you may not be able to use it.
I've only been able to confirm that it works with 3.5 version of python and 1.1 version of Tensorflow.

**Comment by ntreepoint** [comment]
Hi. My bad, meantime i found the (silly) issue. A txt file included in the picture training folder was causing the error.
Thank you for your support
