### ISSUE TITLE
I hope you can help me. Thank you.

### ISSUE THREAD

**Issue by xbackj** [itsuki8914/ESRGAN-TensorFlow#6]
D:\python3.6.4\python.exe E:/ESRGAN-TensorFlow-master/main.py
read images
54.1898 sec took reading
train_lr has 800 files
read images
0.0000 sec took reading
val_lr has 0 files
(4, 96, 96, 3)
54.52185583114624 sec took sampling
Traceback (most recent call last):
  File "E:/ESRGAN-TensorFlow-master/main.py", line 299, in <module>
    main()
  File "E:/ESRGAN-TensorFlow-master/main.py", line 85, in main
    fake_y = buildESRGAN_d(y)
  File "E:\ESRGAN-TensorFlow-master\model.py", line 145, in buildESRGAN_d
    n_b, n_h, n_w, n_f = [int(x) for x in h.get_shape()]  # h.get_shape()
  File "E:\ESRGAN-TensorFlow-master\model.py", line 145, in <listcomp>
    n_b, n_h, n_w, n_f = [int(x) for x in h.get_shape()]  # h.get_shape()
TypeError: __int__ returned non-int (type NoneType)

Process finished with exit code 1

**Comment by Rion12** [comment]
hey @xbackj did you get any solution of this?
